### ISSUE TITLE
Crear método revert en la clase Point

### ISSUE THREAD

**Issue by xavism** [xavism/IWVG.SwC.xavism#1]
Esta issue tiene como principal tarea crear el método revert() , que consiste en girar los puntos x, y.

Por ejemplo, si tenemos un Point = (4,2), al aplicar el metodo revert, el Point pasará a ser (2, 4).

**Comment by borja94** [comment]
Hola Xavi.
La descripción queda un poco confusa con respecto al titulo.
Supongo que habrás querido referiste a la clase Point ya que el titulo hace referencia a esa clase.
Lo voy  hacer sobre la clase Point, si esto es error siempre hay tiempo para volver a atrás.
Un saludo

**Comment by borja94** [comment]
Hola Xavi.
Ya la tengo hecha pero dejo que la cierres tu por si acaso no estuviese bien la mejora que he hecho.
Un saludo.

**Comment by xavism** [comment]
Tienes razon @borja94 , ya he editado la tarea. La reviso y te comento.

**Comment by xavism** [comment]
Esta perfe Borja, cierro issue
