### ISSUE TITLE
Crear método nameToUpperCase en la clase User

### ISSUE THREAD

**Issue by xavism** [xavism/IWVG.SwC.xavism#2]
El objetivo de esta tarea consiste en crear el método nameToUpperCase en la clase User, el resultado será un String con el nombre original pero en mayúsculas.

Por ejemplo, si en la clase User tenemos name = Robert, el método nameToUpperCase devolverá un String = 'ROBERT'.

**Comment by egraciani** [comment]
Hecho. Cambiado en issue#02 y añadido test. Hecho el merge a develop.
