### ISSUE TITLE
Crear el método major en la clase Fraction

### ISSUE THREAD

**Issue by xavism** [xavism/IWVG.SwC.xavism#4]
El objetivo de esta tarea es crear el método major(Fraction b), donde se compara si la propia Fracción de la clase es mayor a otra Fracción obtenida como argumento.

Por ejemplo, si tenemos la propia clase Fraction = (2/4) y otra Fraction b = (3/10), el resultado de major(b) será un boolean = true.

**Comment by borja94** [comment]
Hola Xavi.
Ya he realizado la mejora que has pedido en este issue. y cierro la issue.
Un saludo.
