### ISSUE TITLE
Crear el método multiply en la clase Fraction

### ISSUE THREAD

**Issue by xavism** [xavism/IWVG.SwC.xavism#5]
El objetivo de esta tarea es crear el método multiply(Fraction b), donde se multiplicará la propia Fracción de la clase con otra Fracción obtenida como argumento.

Por ejemplo, si tenemos la propia clase Fraction = (2/4) y otra Fraction b = (3/10), el resultado de multiply(b) será una nueva instancia de la clase Fraction = (6/40)

**Comment by egraciani** [comment]
Hecho. Cambios realizados en issue#05 y hecho el merge en develop.
