### ISSUE TITLE
Crear el método divide en la clase Fraction

### ISSUE THREAD

**Issue by xavism** [xavism/IWVG.SwC.xavism#6]
El objetivo de esta tarea es crear el método divide(Fraction b), donde se dividirá la propia Fracción de la clase con otra Fracción obtenida como argumento.

Por ejemplo, si tenemos la propia clase Fraction = (2/4) y otra Fraction b = (3/10), el resultado de divide(b) será una nueva instancia de la clase Fraction = (20/12)

**Comment by jonh88** [comment]
Buenas!

Terminé la tarea!

Saludos
